### PR TITLE
Polymorphic types should have a virtual destructor

### PR DESCRIPTION
**Pull request by uecasm**
(It annoys `clang-tidy`.)

### CODE REVIEW

**Comment by foonathan** [comment]
clang-tidy is wrong here. The destructor is protected which means the reason for having a virtual destructor (delete base class pointer) doesn't apply: you can't delete a base class pointer. Instead you always create a non-abstract type.

**Comment by uecasm** [comment]
Actually it's correct.  The destructor of `map_database` is public, which means that you could try to destroy its derived types (such as `thread_safe_database<map_database>`) polymorphically, which would break things.

**Comment by foonathan** [comment]
You're correct, however the proper fix would be to change thread_safe_database to use composition instead.

**Comment by uecasm** [comment]
Why is it so terrible to give `basic_database` a public virtual destructor?  Presumably the reason why `basic_database` exists in the first place is to allow people to write their own custom derived types anyway, and they might want to do so polymorphically since `string_id` itself only uses that interface.

**Comment by foonathan** [comment]
Yeah, you're right.

**Pull request merged**
